name: Test Action

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-${{ matrix.ubuntu_version }}

    strategy:
      fail-fast: false
      matrix:
        include:
          # ROS1
          - ros_distro: noetic
            debian_distro: focal
            ubuntu_version: '20.04'
            packages_dir: test/packages-ros1

          - ros_distro: melodic
            debian_distro: bionic
            ubuntu_version: '18.04'
            packages_dir: test/packages-ros1

          # ROS2
          - ros_distro: jazzy
            debian_distro: noble
            ubuntu_version: '24.04'
            packages_dir: test/packages-ros2

          - ros_distro: iron
            debian_distro: jammy
            ubuntu_version: '22.04'
            packages_dir: test/packages-ros2

          - ros_distro: humble
            debian_distro: jammy
            ubuntu_version: '22.04'
            packages_dir: test/packages-ros2

          - ros_distro: galactic
            debian_distro: focal
            ubuntu_version: '20.04'
            packages_dir: test/packages-ros2

          - ros_distro: foxy
            debian_distro: focal
            ubuntu_version: '20.04'
            packages_dir: test/packages-ros2

          - ros_distro: eloquent
            debian_distro: bionic
            ubuntu_version: '18.04'
            packages_dir: test/packages-ros2

          - ros_distro: dashing
            debian_distro: bionic
            ubuntu_version: '18.04'
            packages_dir: test/packages-ros2

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Test ${{ matrix.ros_distro }} packages
        uses: ./
        with:
          ros_distro: ${{ matrix.ros_distro }}
          debian_distro: ${{ matrix.debian_distro }}
          packages_dir: ${{ matrix.packages_dir }}
