name: Test Action

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-${{ matrix.ubuntu_version }}

    strategy:
      fail-fast: false
      matrix:
        include:
          # ROS2 - Currently supported distros only
          - ros_distro: rolling
            debian_distro: noble
            ubuntu_version: '24.04'
            packages_dir: test/packages-ros2

          - ros_distro: kilted
            debian_distro: noble
            ubuntu_version: '24.04'
            packages_dir: test/packages-ros2

          - ros_distro: jazzy
            debian_distro: noble
            ubuntu_version: '24.04'
            packages_dir: test/packages-ros2

          - ros_distro: humble
            debian_distro: jammy
            ubuntu_version: '22.04'
            packages_dir: test/packages-ros2

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Test ${{ matrix.ros_distro }} packages
        uses: ./
        with:
          ros_distro: ${{ matrix.ros_distro }}
          debian_distro: ${{ matrix.debian_distro }}
          packages_dir: ${{ matrix.packages_dir }}
